networks:
  internal:
    driver: bridge

services:
  # API Gateway
  api-gateway:
    image: eclipse-temurin:25-jdk
    container_name: api-gateway
    working_dir: /app
    volumes:
      - ./api-gateway/build/libs:/app/libs
    command: ["java", "-jar", "libs/api-gateway-0.0.1-SNAPSHOT.jar"]
    networks:
      - internal
    ports:
      - "4000:4000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - auth-service
      - identity-service

  # Auth Service
    image: postgres:latest
    networks:
      internal:
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: thomaskyaw
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - /Users/thomaskyaw/Documents/saas_docker_db_volumes/identity-service-db:/var/lib/postgresql/data

  auth-service-db:
    image: postgres:17

    networks:
      - internal
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: thomaskyaw
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - /Users/thomaskyaw/Documents/docker_db_volumes/auth-service-db:/var/lib/postgresql/data

  # Auth Service
  auth-service:
    image: eclipse-temurin:25-jdk
    volumes:
      - ./auth-service/build/libs/auth-service-0.0.1-SNAPSHOT.jar:/app.jar
    command: java -jar /app.jar

    networks:
      - internal
    ports:
      - "4001:4001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: thomaskyaw
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      JWT_SECRET: ${JWT_SECRET}
      IDENTITY_SERVICE_HOST: identity-service
      IDENTITY_SERVICE_PORT: 9090
    depends_on:
      - auth-service-db
      - identity-service

  # Identity Service
  identity-service:
    image: eclipse-temurin:25-jdk
    volumes:
      - ./identity-service/build/libs/identity-service-0.0.1-SNAPSHOT.jar:/app.jar
    command: java -jar /app.jar

    networks:
      - internal
    ports:
      - "4002:4002"
    environment:
#      BILLING_SERVICE_ADDRESS: billing-service
#      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_DATASOURCE_URL: jdbc:postgresql://identity-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: thomaskyaw
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_SQL_INIT_MODE: always
      GRPC_SERVER_PORT: 9090
    depends_on:
#      - kafka
      - identity-service-db
